### ISSUE TITLE
Cannot read .txt file?

### ISSUE THREAD

**Issue by SirPhemmiey** [jaywcjlove/github-action-read-file#13]
Hello, 

I'm using this action but i don't know why it can't be read. I'm passing a `.txt` file to the path and i'm getting this message:
<img width="1156" alt="Screenshot 2024-05-15 at 11 15 10" src="https://github.com/jaywcjlove/github-action-read-file/assets/22390818/0cd22445-c4f1-4068-89f5-e0009fc40889">

Can you help on this, please?

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/github-action-read-file/blob/8498b54a70094fa5eaa02caca1af2da7e84121b4/src/index.ts#L24-L28

@SirPhemmiey Maybe you need to check if your configuration is correct, if the file exists, or if the file is on the correct Git branch.

**Comment by SirPhemmiey** [comment]
I'll be closing this. I used another action and it worked. 

Thanks.
